# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nian Shao
description:      'PhD Student at EPFL <br> Email: nian.shao@epfl.ch'
baseurl:          /

paginate:         5

