# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nian Shao
description:      'PhD Student at EPFL'
baseurl:          /

paginate:         5

