# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nian Shao
description:      'PhD Student at EPFL <br> <a href="mailto:nian.shao@epfl.ch"> nian.shao@epfl.ch</a>'
baseurl:          /

paginate:         5

